---

- name: Create XSIBackup directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ xsibackup_working_dir }}"
    - "{{ xsibackup_working_dir }}/xsibackup"
    - "{{ xsibackup_working_dir }}/xsibackup-{{ xsibackup_version }}"
    - "{{ xsibackup_backup_dir }}"

- name: Copy XSIBackup {{ xsibackup_version }} folder
  copy:
    src: "XSIBACKUP-FREE-{{ xsibackup_version }}/"
    dest: "{{ xsibackup_working_dir }}/xsibackup-{{ xsibackup_version }}"
    force: no

- name: Mark EULA as read
  lineinfile:
    path: "{{ xsibackup_working_dir }}/xsibackup/EULA"
    regexp: "^read="
    line: "read=1"

- name: Symlink XSIBackup directory to versioned folder
  file:
    src: "{{ xsibackup_working_dir }}/xsibackup-{{ xsibackup_version }}"
    dest: "{{ xsibackup_working_dir }}/xsibackup"
    state: link
    force: true

- name: Apply permissions for XSIBackup folders
  file:
    path: "{{ item.path }}"
    mode: 0700
    recurse: "{{ item.recurse }}"
  loop:
    - path: "{{ xsibackup_working_dir }}/xsibackup/xsibackup"
      recurse: false
    - path: "{{ xsibackup_working_dir }}/xsibackup/src"
      recurse: true
    - path: "{{ xsibackup_working_dir }}/xsibackup/bin"
      recurse: true

- name: Create XSIBackup jobs
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ xsibackup_working_dir }}/xsibackup/jobs/{{ item.name }}"
    mode: 0700
  loop: "{{ xsibackup_jobs|flatten(levels=1) }}"

- name: Add jobs to XSIBackup crontab
  lineinfile:
    path: "{{ xsibackup_working_dir }}/xsibackup/conf/root-crontab"
    regexp: ".*jobs/{{ item.name }}\"$"
    line: "{{ item.cron }} \"{{ xsibackup_working_dir }}/xsibackup/jobs/{{ item.name }}\""
  loop: "{{ xsibackup_jobs|flatten(levels=1) }}"

- name: Copy clean-backup script
  copy:
    src: clean-backups.py
    dest: "{{ xsibackup_working_dir }}"
    mode: 0700

- name: Add clean-backup script to crontab
  lineinfile:
    path: "{{ xsibackup_working_dir }}/xsibackup/conf/root-crontab"
    regexp: "clean-backups.py"
    line: "{{ xsibackup_cleaner.cron }} /bin/python '{{ xsibackup_working_dir }}/clean-backups.py' -p {{ xsibackup_backup_dir }} -r 'backup*' -k {{ xsibackup_cleaner.days_to_keep }}"

- name: Install crontab
  shell: "{{ xsibackup_working_dir }}/xsibackup/xsibackup --install-cron --exec=yes"
  register: result
  changed_when: "'successfully' in result.stdout"
  failed_when: "result.rc != -9"

- name: Update crontab
  shell: "{{ xsibackup_working_dir }}/xsibackup/xsibackup --update-cron --exec=yes"
  failed_when: "result.rc != -9"
